--
-- PostgreSQL database dump
--

\restrict jepagVdKBUECWq1FcB7bhAR3gXi2eW5OCukma0DpA2izFQUmn934N4TPX3Nudrf

-- Dumped from database version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: medicaluser
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO medicaluser;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: appointments; Type: TABLE; Schema: public; Owner: medicaluser
--

CREATE TABLE public.appointments (
    id bigint NOT NULL,
    app_date date NOT NULL,
    app_time time(0) without time zone NOT NULL,
    reason character varying(200) NOT NULL,
    doctor_id bigint NOT NULL,
    patient_id bigint NOT NULL
);


ALTER TABLE public.appointments OWNER TO medicaluser;

--
-- Name: appointments_id_seq; Type: SEQUENCE; Schema: public; Owner: medicaluser
--

ALTER TABLE public.appointments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctors; Type: TABLE; Schema: public; Owner: medicaluser
--

CREATE TABLE public.doctors (
    id bigint NOT NULL,
    clinic character varying(80),
    name character varying(80) NOT NULL
);


ALTER TABLE public.doctors OWNER TO medicaluser;

--
-- Name: doctors_id_seq; Type: SEQUENCE; Schema: public; Owner: medicaluser
--

ALTER TABLE public.doctors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patients; Type: TABLE; Schema: public; Owner: medicaluser
--

CREATE TABLE public.patients (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    first_name character varying(80) NOT NULL,
    last_name character varying(80) NOT NULL,
    national_id character varying(20) NOT NULL,
    phone character varying(20)
);


ALTER TABLE public.patients OWNER TO medicaluser;

--
-- Name: patients_id_seq; Type: SEQUENCE; Schema: public; Owner: medicaluser
--

ALTER TABLE public.patients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: appointments; Type: TABLE DATA; Schema: public; Owner: medicaluser
--

COPY public.appointments (id, app_date, app_time, reason, doctor_id, patient_id) FROM stdin;
1	2026-02-25	10:30:00	General checkup	1	1
\.


--
-- Data for Name: doctors; Type: TABLE DATA; Schema: public; Owner: medicaluser
--

COPY public.doctors (id, clinic, name) FROM stdin;
1	Kardiyoloji	Dr. Emre Hallı
\.


--
-- Data for Name: patients; Type: TABLE DATA; Schema: public; Owner: medicaluser
--

COPY public.patients (id, created_at, first_name, last_name, national_id, phone) FROM stdin;
1	2026-02-25 00:19:11.81345+03	Emir	yılmaz	12345678901	05555555555
\.


--
-- Name: appointments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medicaluser
--

SELECT pg_catalog.setval('public.appointments_id_seq', 1, true);


--
-- Name: doctors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medicaluser
--

SELECT pg_catalog.setval('public.doctors_id_seq', 1, true);


--
-- Name: patients_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medicaluser
--

SELECT pg_catalog.setval('public.patients_id_seq', 1, true);


--
-- Name: appointments appointments_pkey; Type: CONSTRAINT; Schema: public; Owner: medicaluser
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);


--
-- Name: doctors doctors_pkey; Type: CONSTRAINT; Schema: public; Owner: medicaluser
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT doctors_pkey PRIMARY KEY (id);


--
-- Name: patients idx_patients_national_id; Type: CONSTRAINT; Schema: public; Owner: medicaluser
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT idx_patients_national_id UNIQUE (national_id);


--
-- Name: patients patients_pkey; Type: CONSTRAINT; Schema: public; Owner: medicaluser
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT patients_pkey PRIMARY KEY (id);


--
-- Name: appointments uk_doctor_date_time; Type: CONSTRAINT; Schema: public; Owner: medicaluser
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT uk_doctor_date_time UNIQUE (doctor_id, app_date, app_time);


--
-- Name: appointments fk8exap5wmg8kmb1g1rx3by21yt; Type: FK CONSTRAINT; Schema: public; Owner: medicaluser
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk8exap5wmg8kmb1g1rx3by21yt FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- Name: appointments fkmujeo4tymoo98cmf7uj3vsv76; Type: FK CONSTRAINT; Schema: public; Owner: medicaluser
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fkmujeo4tymoo98cmf7uj3vsv76 FOREIGN KEY (doctor_id) REFERENCES public.doctors(id);


--
-- PostgreSQL database dump complete
--

\unrestrict jepagVdKBUECWq1FcB7bhAR3gXi2eW5OCukma0DpA2izFQUmn934N4TPX3Nudrf

